import AppKit
import Foundation
import Observation

/// Runs a Finder-navigation drill: opens a tmp folder with a grid of
/// files, walks the student through a series of reps where they must
/// move the selection from a start file to a target file using hjkl
/// (via kindaVim) or arrow keys. Mirrors `ExerciseEngine`'s state
/// machine so the existing coaching/progress surfaces can be adapted.
///
/// This engine is standalone for now — not yet wired into Curriculum
/// or the lesson step controller. Invoked from the Debug menu / app
/// command channel until it's exercised enough to graduate.
@Observable
@MainActor
final class FinderDrillEngine {
    enum State: Equatable {
        case idle
        case preparing
        /// Waiting for Finder to land on the rep's start file before
        /// we begin counting moves + time. Protects against the
        /// transient observer fires between "we asked to select the
        /// start" and "Finder actually shows the start selected".
        case seeding
        case active
        case repCompleted
        case drillCompleted
    }

    /// One rep's definition: start the user at the folder at
    /// `startIndex`, target is the folder at `targetIndex`. Both
    /// refer to positions in the run's shuffled name list —
    /// resolved to real folder names via `folderNames`.
    struct Rep: Equatable {
        let startIndex: Int
        let targetIndex: Int
    }

    struct RepResult: Equatable {
        let rep: Rep
        let moves: Int
        let timeSeconds: TimeInterval
    }

    private(set) var state: State = .idle
    private(set) var folder: URL?
    private(set) var reps: [Rep] = []
    /// Human-readable goal of this drill, shown at the top of the
    /// coaching panel so the student always has context.
    private(set) var title: String = "Finder Navigation"
    private(set) var subtitle: String = "Move the selection to each red file using h j k l"
    private(set) var completedRepIndex: Int = 0
    private(set) var moveCount: Int = 0
    private(set) var elapsedTime: TimeInterval = 0
    private(set) var results: [RepResult] = []
    /// The selection we've most recently observed. Used to dedupe the
    /// AXObserver's 2–3x redundant fires per real change, and as the
    /// pre-state so rep-start self-selection isn't scored as a move.
    private(set) var currentSelection: String?

    /// Called once when the drill transitions to `.drillCompleted`.
    /// Lets callers run wrap-up UX (close Finder windows, fire
    /// confetti, return focus to the tutor) without the engine having
    /// to know about any of it.
    var onDrillCompleted: (() -> Void)?

    private let observer = FinderSelectionObserver()
    private var startTime: Date?
    private var timer: Timer?
    private var files: [URL] = []
    private var previousTargetURL: URL?
    private var previousTargetIndex: Int?
    /// The lowercase names each slot had at drill start. Used to
    /// restore a target folder's name when the rep advances.
    private var originalFolderNames: [String] = []
    /// ALL-CAPS target names already used in this drill; prevents
    /// picking the same word twice across reps.
    private var usedTargetNames: Set<String> = []

    /// Deterministic but per-run shuffle of the vivid target palette,
    /// one key per rep. If more reps than palette entries, wraps.
    private func assignedTargetIconKeys(repCount: Int) -> [String] {
        let palette = FinderDrillPrototype.targetIconKeys.shuffled()
        return (0..<repCount).map { palette[$0 % palette.count] }
    }
    /// The vivid target icon key for each rep, in order. Shuffled
    /// per drill so consecutive runs don't feel identical. The
    /// engine applies the current rep's color on rep start and
    /// restores the previous target to neutral on advance.
    private(set) var repTargetIconKeys: [String] = []

    /// Key of the current rep's vivid icon — used by the coaching
    /// panel to tint the "Move to …" label and dot to match the
    /// folder color.
    var currentTargetIconKey: String {
        guard repTargetIconKeys.indices.contains(completedRepIndex)
        else { return FinderDrillPrototype.targetIconKeys.first ?? "furry-target-magenta" }
        return repTargetIconKeys[completedRepIndex]
    }

    /// The actual folder names for this run, indexed by position.
    /// Generated by the prototype from a pool of random words —
    /// target positions get ALL-CAPS names so they stand out.
    private(set) var folderNames: [String] = []

    /// The displayed name of the current rep's target. Used by the
    /// coaching panel's "Move to …" label.
    var currentTargetName: String {
        guard let rep = currentRep, folderNames.indices.contains(rep.targetIndex)
        else { return "target" }
        return folderNames[rep.targetIndex]
    }

    /// The set of indices that act as a target in any rep. These
    /// folders get the vivid target icon when the drill opens; the
    /// rest get palette colors.
    private var targetIndexSet: Set<Int> {
        Set(reps.map { $0.targetIndex })
    }

    var currentRep: Rep? {
        guard completedRepIndex < reps.count else { return nil }
        return reps[completedRepIndex]
    }

    // MARK: - Lifecycle

    /// Starts a drill: materialize tmp folder, open Finder, install
    /// the AX observer, run reps sequentially. Returns false if the
    /// setup fails (e.g. AX not trusted or Finder not responding).
    @discardableResult
    func start(reps: [Rep],
               title: String = "Finder Navigation",
               subtitle: String = "Navigate to the goal folder using h j k l",
               rows: Int = 3,
               cols: Int = 4) async -> Bool {
        guard !reps.isEmpty else { return false }
        stop()
        state = .preparing
        self.reps = reps
        self.title = title
        self.subtitle = subtitle
        self.completedRepIndex = 0
        self.results = []

        let count = rows * cols
        let targetIndices = Set(reps.map { $0.targetIndex })
        let names = FinderDrillPrototype.generateFolderNames(
            count: count,
            targetIndices: targetIndices
        )
        self.folderNames = names
        self.originalFolderNames = names
        self.usedTargetNames = []
        self.previousTargetIndex = nil
        self.repTargetIconKeys = assignedTargetIconKeys(repCount: reps.count)

        guard let prep = await FinderDrillPrototype.run(
            names: names,
            rows: rows,
            cols: cols
        ) else {
            state = .idle
            return false
        }
        self.folder = prep.folder
        self.files = prep.files

        let started = observer.start { [weak self] selection in
            self?.selectionDidChange(to: selection)
        }
        guard started else {
            state = .idle
            return false
        }

        startRep()
        return true
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        observer.stop()
        if let folder { FinderDrillPrototype.cleanUp(folder) }
        folder = nil
        files = []
        state = .idle
    }

    // MARK: - Rep machine

    private func startRep() {
        guard let rep = currentRep else {
            completeDrill()
            return
        }
        moveCount = 0
        elapsedTime = 0

        // Between reps: rename the previous target back to its
        // original lowercase name + restore the neutral icon, then
        // rename THIS rep's target to a fresh ALL-CAPS label and
        // stamp the vivid icon. Renaming-plus-setIcon forces a
        // Finder refresh so the new color actually shows.
        if let folder, folderNames.indices.contains(rep.targetIndex) {
            if let prev = previousTargetIndex,
               originalFolderNames.indices.contains(prev),
               folderNames.indices.contains(prev) {
                let prevURL = folder.appendingPathComponent(
                    folderNames[prev], isDirectory: true
                )
                let original = originalFolderNames[prev]
                if let restored = FinderDrillPrototype.renameAndSetIcon(
                    from: prevURL, to: original, iconKey: "furry-neutral"
                ) {
                    folderNames[prev] = restored.lastPathComponent
                }
            }

            let currentURL = folder.appendingPathComponent(
                folderNames[rep.targetIndex], isDirectory: true
            )
            let targetName = FinderDrillPrototype.randomTargetName(
                excluding: usedTargetNames
            )
            usedTargetNames.insert(targetName)
            if let renamed = FinderDrillPrototype.renameAndSetIcon(
                from: currentURL, to: targetName,
                iconKey: currentTargetIconKey
            ) {
                folderNames[rep.targetIndex] = renamed.lastPathComponent
                previousTargetIndex = rep.targetIndex
            }
        }

        let startName = folderNames[rep.startIndex]
        state = .seeding
        _ = FinderGrid.selectFile(named: startName)
        AppLogger.shared.info("finderDrill", "repStart", fields: [
            "index": "\(completedRepIndex)",
            "start": startName,
            "target": folderNames[rep.targetIndex]
        ])
        // If Finder already has the start selected (previous rep's
        // target happened to match), the observer won't fire and
        // we'd be stuck in .seeding. Check now and advance.
        if FinderDrillPrototype.readFinderSelection() == startName {
            currentSelection = startName
            activateRep()
        }
    }

    /// Called when we observe the student actually at the start file.
    /// Transitions the rep from `.seeding` into `.active` and starts
    /// the clock.
    private func activateRep() {
        state = .active
        startTime = Date()
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.1, repeats: true) { [weak self] _ in
            Task { @MainActor in
                guard let self, let t = self.startTime, self.state == .active else { return }
                self.elapsedTime = Date().timeIntervalSince(t)
            }
        }
    }

    private func selectionDidChange(to selection: String?) {
        guard let selection else { return }
        if state == .seeding {
            currentSelection = selection
            if let rep = currentRep,
               folderNames.indices.contains(rep.startIndex),
               selection == folderNames[rep.startIndex] {
                activateRep()
            }
            return
        }
        guard state == .active else { return }
        guard selection != currentSelection else { return }
        currentSelection = selection
        moveCount += 1

        AppLogger.shared.info("finderDrill", "repMove", fields: [
            "index": "\(completedRepIndex)",
            "selection": selection,
            "moves": "\(moveCount)"
        ])

        if let rep = currentRep,
           folderNames.indices.contains(rep.targetIndex),
           selection == folderNames[rep.targetIndex] {
            completeRep()
        }
    }

    private func completeRep() {
        guard let rep = currentRep else { return }
        timer?.invalidate()
        timer = nil
        let elapsed = startTime.map { Date().timeIntervalSince($0) } ?? 0
        let result = RepResult(rep: rep, moves: moveCount, timeSeconds: elapsed)
        results.append(result)
        AppLogger.shared.info("finderDrill", "repComplete", fields: [
            "index": "\(completedRepIndex)",
            "moves": "\(moveCount)",
            "time": String(format: "%.2f", elapsed)
        ])
        completedRepIndex += 1
        state = .repCompleted

        // Advance after a short beat so the student sees the hit.
        Task { @MainActor in
            try? await Task.sleep(for: .milliseconds(700))
            startRep()
        }
    }

    private func completeDrill() {
        timer?.invalidate()
        timer = nil
        observer.stop()
        state = .drillCompleted
        let totalMoves = results.reduce(0) { $0 + $1.moves }
        let totalTime = results.reduce(0) { $0 + $1.timeSeconds }
        AppLogger.shared.info("finderDrill", "drillComplete", fields: [
            "reps": "\(results.count)",
            "moves": "\(totalMoves)",
            "time": String(format: "%.2f", totalTime)
        ])
        onDrillCompleted?()
    }

    /// Aggregate across all completed reps — for the ring progress +
    /// metrics readouts in the coaching panel (matches the tutor's
    /// left-rail DrillSidebarSection).
    var totalMoves: Int { results.reduce(0) { $0 + $1.moves } }
    var totalTime: TimeInterval { results.reduce(0) { $0 + $1.timeSeconds } }
    var drillProgress: Double {
        guard !reps.isEmpty else { return 0 }
        return Double(completedRepIndex) / Double(reps.count)
    }

    /// The grid delta from the student's current selection to the
    /// target, in (rightward, downward) cells. Positive dx = press l,
    /// negative dx = press h; positive dy = press j, negative dy =
    /// press k. Nil if we can't resolve either cell in Finder's AX
    /// tree (window not frontmost, etc.).
    var directionToTarget: (dx: Int, dy: Int)? {
        guard let rep = currentRep,
              let selection = currentSelection,
              folderNames.indices.contains(rep.targetIndex),
              let layout = FinderGrid.readLayout(),
              let from = layout.cell(named: selection),
              let to = layout.cell(named: folderNames[rep.targetIndex])
        else { return nil }
        return (to.col - from.col, to.row - from.row)
    }

    /// Rep-specific instruction line — "Across the top row", "Back
    /// home", etc. Auto-derived from the start→target geometry so the
    /// coaching panel title shifts per rep without the caller needing
    /// to hand-write labels. Falls back to a generic string if the
    /// grid isn't resolvable yet.
    var currentRepInstruction: String {
        guard let rep = currentRep,
              folderNames.indices.contains(rep.startIndex),
              folderNames.indices.contains(rep.targetIndex),
              let layout = FinderGrid.readLayout(),
              let from = layout.cell(named: folderNames[rep.startIndex]),
              let to = layout.cell(named: folderNames[rep.targetIndex]) else {
            return "Find the \(currentTargetName) folder"
        }
        let dx = to.col - from.col
        let dy = to.row - from.row
        switch (dx.signum(), dy.signum()) {
        case (0, 0):   return "You're already there"
        case (_, 0):   return dx > 0 ? "Move right across the row" : "Move left across the row"
        case (0, _):   return dy > 0 ? "Move down the column" : "Move up the column"
        case (1, 1):   return "Move down and to the right"
        case (1, -1):  return "Move up and to the right"
        case (-1, 1):  return "Move down and to the left"
        case (-1, -1): return "Move up and to the left"
        default:       return "Find the red file"
        }
    }
}
